### PR TITLE
Update icu pin

### PR DESCRIPTION
**Pull request by ocefpaf**
Re-sending #14 because due to some weird  thing I could not re-open it.

### CODE REVIEW

**Comment by croth1** [comment]
unfortunately travis is slow atm... fontconfig for mac is not yet shipped.

**Comment by ocefpaf** [comment]
> unfortunately travis is slow atm... fontconfig for mac is not yet shipped.

Don't worry I am monitoring the situation and re-starting things accordingly. (Closing this for now to avoid an accidental merge. Sorry about the noise.)

**Comment by croth1** [comment]
@ocefpaf, I took the liberty of reopening and rerunning travis. Shall we merge this?

**Comment by ocefpaf** [comment]
> @ocefpaf, I took the liberty of reopening and rerunning travis. Shall we merge this?

Thanks. Looks OK but I added another commit with a test to check if the `ICU` links are OK (`conda-inspect`) and re-rendered. Once that passes we can merge it.

**Pull request merged**
