### PR TITLE
pin libwebp library

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please submit a PR to the webpage repo to add this pinning with some details about why it was selected?

**Comment by bgruening** [comment]
@jakirkham I don't know. I had hoped libwebp is following the major, minor approach. We can also pin to `0.5.2` if this is more save. But we need to pin it starts breaking packages afaik.

**Comment by jakirkham** [comment]
Normally we use [ABI Laboratory]( https://abi-laboratory.pro ) to track ABI changes. Here is the [report]( https://abi-laboratory.pro/tracker/timeline/libwebp/ ) for `libwebp`. So it seems like major minor pinning as was done here is ok. Just would add a PR to add this change to this [list]( https://github.com/conda-forge/conda-forge.github.io/blob/0661e2ecf4b213ddf36350ca100a5a820eb17eb7/scripts/pin_the_slow_way.py#L40-L85 ). Also would include a link to the ABI report in that PR. Should be pretty straightforward.

**Comment by bgruening** [comment]
@jakirkham thanks. Done here: https://github.com/conda-forge/conda-forge.github.io/pull/423

**Comment by croth1** [comment]
shall we merge this?

**Comment by jakirkham** [comment]
LGTM

**Comment by croth1** [comment]
thanks @bgruening

**Comment by bgruening** [comment]
Thanks for the merge!

**Pull request merged**
